services:
  backend:
    build: .
    container_name: grocery_api
    ports:
      - 8000:8000
    env_file: .env
    environment:
      TZ: "Asia/Kathmandu"
    command: npm start
    depends_on:
      database:
        condition: service_started
        restart: true
    develop:
      watch:
        - action: sync
          path: .
          ignore:
            - node_modules/
          target: /app
        - action: rebuild
          path: ./package.json
        - action: rebuild
          path: ./.env
        - action: rebuild
          path: ./swagger
  database:
    image: postgres:16.3-alpine3.19
    ports:
      - 5432:5432
    env_file: .env
    environment:
      TZ: "Asia/Kathmandu"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    develop:
      watch:
        - path: ./.env
          action: sync+restart
          target: /app

volumes:
  postgres_data:
