services:
  backend:
    build: .
    container_name: grocery_api
    ports:
      - 8000:8000
    env_file: .env
    environment:
      TZ: "Asia/Kathmandu"
    command: npm start
    develop:
      watch:
        - action: sync
          path: .
          ignore:
            - node_modules/
          target: /app
        - action: rebuild
          path: ./package.json
        - action: rebuild
          path: ./.env
