parameters:
  name:
    type: string
    description: Your visible name on platform
  username:
    type: string
    description: username to login with
  password:
    type: string
    description: a strong password
  email:
    type: string
    description: a unique email address
  error:
    type: string
    description: Indicates the error message
  message:
    type: string
    description: Message from server
