components:
  schemas:
    Register:
      $ref: "#/components/Register"
      example:
        name: "John Doe"
        username: username
        password: password
        email: email@personal.com

    Login:
      $ref: "#/components/Login"
      example:
        email: email@personal.com
        password: password

    Error:
      $ref: "#/components/Error"
      example:
        error: Some error occured

    AuthResponse:
      type: object
      properties:
        message:
          type: string
          description: Message of execution
        token:
          type: string
          description: JWT token for later access
